


version: '3'
services:
  master:
    image: redis:latest
    container_name: redis_master  #master节点
    volumes:
      - ./master/conf/redis.conf:/etc/redis/redis.conf
      - ./master/data:/data
    networks:
      redis_network:
        ipv4_address: 172.22.1.2
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"  #这句话就是要加载这个路径下的配置
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    ports:
      - "6379:6379"

  slave1:
    image: redis:latest
    container_name: redis_slave_1   #slave1节点
    volumes:
      - ./slave1/conf/redis.conf:/etc/redis/redis.conf
      - ./slave1/data:/data
    networks:
      redis_network:
        ipv4_address: 172.22.1.3
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    ports:
      - "6380:6379"

  slave2:
    image: redis:latest
    container_name: redis_slave_2   #slave2节点
    volumes:
      - ./slave2/conf/redis.conf:/etc/redis/redis.conf
      - ./slave2/data:/data
    networks:
      redis_network:
        ipv4_address: 172.22.1.4
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    ports:
      - "6381:6379"

  sentinel1:
    image: redis:latest
    container_name: redis_sentinel_1  #sentinel1节点
    ports:
      - "26379:26379"
    volumes:
      - ./sentinel1/conf/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      redis_network:
        ipv4_address: 172.22.1.5
    command: /bin/bash -c "redis-sentinel /usr/local/etc/redis/sentinel.conf"

  sentinel2:
    image: redis:latest
    container_name: redis_sentinel_2 #sentinel2节点
    ports:
      - "26380:26379"
    volumes:
      - ./sentinel2/conf/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      redis_network:
        ipv4_address: 172.22.1.6
    command: /bin/bash -c "redis-sentinel /usr/local/etc/redis/sentinel.conf"

  sentinel3:
    image: redis:latest
    container_name: redis_sentinel_3 #sentinel3节点
    ports:
      - "26381:26379"
    volumes:
      - ./sentinel3/conf/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      redis_network:
        ipv4_address: 172.22.1.7
    command: /bin/bash -c "redis-sentinel /usr/local/etc/redis/sentinel.conf"

networks:
  redis_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.1.0/24

